apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dream-dev
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
  type: NodePort
